% readfile_main.m

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Description: read a text file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% case1: Read a text file of both numeric and non-numeric data
% input file: a map file generated by the plink software
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

infile = 'G1K_chr19_CEU.map';

% chrno: chromosome numbers, snp_ids: snp identifiers, gd: genetic distance
% (morgan), bp: base-pair positions
formatStr = '%s %s %f %f';
[chrno, snp_ids, gd, bp] = readfile_mixed_format(infile, formatStr);

% save the values in a mat file so that simply load it rather than reading the input file everytime
save case1.mat chrno snp_ids gd bp; 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% case2: Read a text file of both numeric and non-numeric data. Read all
% columns as string and then convert then to appropriate format
% input file: a map file generated by the plink software
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

infile = 'G1K_chr19_CEU.map';

formatStr = '%s %s %s %s';
[chrno, snp_ids, gd, bp] = readfile_mixed_format(infile, formatStr);

gd = str2double(gd);
bp = str2double(bp);

save case2.mat chrno snp_ids gd bp;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% case3: Read ASCII-delimited file of only numeric data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
infile = 'numeric_test.txt';
M = readfile_numeric_data(infile);

save case3.mat M;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% case4: If the delimiter is none of the default ones, specify it.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
infile = 'numeric_test.txt'; 
M = readfile_numeric_data(infile, '\t');

save case4.mat M;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% case5: Read a comma-separated numeric data (CSV) file. If non-numeric 
% data are also contained in the file, call the readfile_mixed_format(...) 
% above that uses textscan().
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
M = readfile_csv(filename);
save case5.mat M;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% case6: Read a Microsoft Excel spreadsheet file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[num,txt,raw] = readfile_excel(filename);   % reads the first worksheet. Default worksheet is the first one.
[num,txt,raw] = excel(filename,sheet);   % reads the specified worksheet

save case5.mat num txt raw;
